### ISSUE TITLE
[BUG] - %counter overwrites existing files

### ISSUE THREAD

**Issue by Dachiko** [receyuki/comfyui-prompt-reader-node#11]
### Summary

I have a lot of images in different formats, but all the names starts with the counter. If possible, I'd like for SD Prompt Saver to calculate the value of %counter taking into account other images in the folder

### Basic Example

Let's say I have next files:
00034 something something.jpg
00134 something something.png
01097.webp

And I have only %counter as a filename in the SD Prompt Saver node. I'd like it to save next generated picture with the name
01098.png
(png or any other format)

PS: thank you for your hard work!

**Comment by Dachiko** [comment]
Just realized that the %counter is very basic, don't account for anything, and SD Prompt Saver happily overwrites existing files with the same name. Now instead of having like 50 new pictures I have only two last generated, what a downturn :(

**Comment by receyuki** [comment]
Actually, this is a known bug, it has been mentioned here receyuki/stable-diffusion-prompt-reader#55, and it will be fixed in the next version (hopefully).

Currently, the %counter of the Prompt Saver uses the mechanism of the original Saver. However, the path and filename on the Prompt Saver are much more complex than the original node, so I may need to completely rewrite the logic of the %counter. 

Please replace it with other placeholders for now, or use the other counters mentioned here receyuki/stable-diffusion-prompt-reader#55 (you may need to ask the questioner about the node’s name).

**Comment by receyuki** [comment]
Fixed in v1.0.1, please update the node to the latest version.
