### ISSUE TITLE
[FEATURE REQUEST] - Compatibility with Image Receiver node (Impact Pack)

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#17]
### Summary

I'm considering different approaches to reduce the number of wires in the AP Workflows without sacrificing understandability of the information flow. 

Among the other things, I'm evaluating the use of Impact Pack's `Image Sender` and `Image Receiver` nodes.

I would place an `Image Sender` node after each image generation node (e.g., KSampler, Detailers) and an `Image Receiver` node just before every `SD Prompt Saver` node.

My test shows that the latter don't play well together. 

After a `KSampler` node generates the image, it passes it to the `Image Sender` node, which correctly passes it to the `Image Receiver` node. However, the `Image Receiver` node doesn't seem to pass the image to the `SD Prompt Saver` node as expected:

<img width="1132" alt="Screenshot 2023-11-03 at 13 22 34" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/d4faeaf1-6c26-4eb9-85d8-b8b7f9964061">

I am not married to the idea of using Impact Pack's Image Sender/Receiver nodes at all costs. I'd just like to have the `SD Prompt Saver` to wirelessly receive the image to save, if possible.

### Basic Example

See screenshot.

**Comment by receyuki** [comment]
In my tests, everything is working fine, at least the Prompt Saver performs the same as the built-in Saver. 

I guess what you mean by 'don't play well together' is that the Saver only updates the image from the first generation after generating the second one. But even when connecting the image receiver to the built-in Saver, this behavior still occurs. So, it seems to be a characteristic of the image receiver rather than something caused by the Saver.

**Comment by alessandroperilli** [comment]
That is correct. I wrongly assumed that behavior was caused by an incompatibility with the SD Prompt Saver. I should have checked the default saver before opening this issue. I'll be more mindful in the future. Thanks for testing it.
