### ISSUE TITLE
[FEATURE REQUEST] - Add "Notes" field to the SD Parameter Generator node

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#32]
### Summary

Very often, I find myself in need of adding a note to the image generation I'm about to queue. It could be a reason why I am doing a certain test, or the purpose of the image, or just to indicate how what was the tool that generated that image.
Accordingly, I manually add a `Multiline Text` node next to the `SD Parameter Generator` node, and then push output that text to both the debug section of my workflow and to the `Extra Info` input of the `SD Prompt Saver` node (see screenshot below).

It works perfectly fine, but it's a lot of extra nodes and wires that we could probably avoid if this field would be part of the `SD Parameter Generator` node. 

### Basic Example

<img width="404" alt="Screenshot 2023-12-05 at 10 13 23" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/a337c16d-32a0-4b9e-a535-4d34dbc64850">

I propose the creation of this field as the very last input box (if possible), and the very last output pin, in the node.

I think it's still within the scope of this node and it would be a QoL improvement. 

Thank you for considering it.

**Comment by receyuki** [comment]
Personally, I think adding this note to the prompt generator is not appropriate.
- This note doesn’t contribute to and isn’t essential for creating images.
- I believe most people don’t need it.
- The most important thing is that, since I cannot add a title in the text box, users might misunderstand its purpose. If I were you, I would prefer to use a separate text box with a title, just like what you are doing now :)

**Comment by alessandroperilli** [comment]
Alright, then. Thank you.
