### ISSUE TITLE
[FEATURE REQUEST] - Explicit pixels dimensions in aspect_ratio drop down for Parameter Generator

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#6]
### Summary

I know we already discussed this, and I tested the current approach extensively in these weeks since you released the new version of Parameter Generator.

My conclusion is that it's really difficult to remember what each ratio means in terms of pixels from the current drop down:
<img width="650" alt="Screenshot 2023-10-25 at 18 26 54" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/049cefa8-54d5-49b8-9754-c96e29265405">

And since the node shows the exact pixels only after queuing a generation, it's a game of guesses, or googling the answer before using ComfyUI, or bookmarking posts like [this one](https://www.reddit.com/r/StableDiffusion/comments/17g2xbf/optimal_sdxl_resolution/). At least, that's what I do now.

It would be really super useful if the node would show each pixel pairing next to each ratio (and according to the selected SD family). 

### Basic Example

1. The user selects SDXL 1024 from the `model_version` drop down.
2. The user sees thinks like "16:9 - 1344x768px" in the `aspect_ratio` drop down.

**Comment by receyuki** [comment]
Hi, I just released stable version of 1.0.0. About this old issue, I haven’t found any way to modify the value of dropdown or textbox in real-time, but I will continue to search for solutions (since this would also improve prompt display). Of course, if you find any custom nodes that have display content changing instantly after modifying input values (including textboxes/dropdown/input boxes), please let me know. There’s a good chance I could find a solution by looking at their source code.

**Comment by alessandroperilli** [comment]
I'm not asking for a real-time change. I think it's not possible. I'm asking to statically describe every pair, like Comfyroll is doing with its `CR Aspect Ratio` node:

<img width="446" alt="Screenshot 2023-10-25 at 21 34 04" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/1b15932c-8ed4-407e-886e-e11a7930170b">

The words "portrait", "landscape" and "cinema" seem unnecessary, but the pixel resolution next to the aspect ratio is what I'm looking for.

**Comment by receyuki** [comment]
Oh alright, then we have a few options:
1. A super long dropdown with 28 items.
2. After the first generation, display the resolution of the chosen model in the dropdown, like comfyroll. However, the downside is that it still requires a generation.
3. Display the resolution of the three models in the same row. e.g. [1:1 - 512x512 | 768x768 | 1024x1024] 
4. Comfyroll chose to divide node into two, a regular version and an SDXL version. It’s a solution, but not a very elegant one.

So, the issue still lies in the fact that the three models have different optimal resolutions. I’m also not sure what the best choice would be.

**Comment by alessandroperilli** [comment]
Of course, option 1 is not an option.
Option 2 is similarly confusing as today's situation, so I'd say neither.
Option 4 would be a nightmare to manage and I would really prefer not.

Option 3 seems the most likely possibility, but I'd explore an alternative:

Is it possible that only a portion of those 28 items appear in the aspect_ratio drop-down, depending on the choice made in the model_version drop down?
It's not a real-time change, but rather an if-then situation, so perhaps possible?

If that's not possible, then either option 3 (as long as it doesn't look ugly or ginormous) or let's stay as it is right now.


P.S.: There's a 5th option: 3 aspect_ratio drop downs, one for each model_version. I think it's very inelegant. At that point, Option 3 seems better. I mentioned it just for the sake of being comprehensive.

**Comment by receyuki** [comment]
What I mean by real-time changes are any changes made before the next generation, because currently, I can only trigger any modifications through generation. Therefore, I cannot modify the aspect ratio after the user modifies the model version (before generating).

How about this, let the dropdown show option 3 by default, and then only show the resolution of the corresponding model after the first generation? Or let the dropdown show 28 items by default, then only show 9 of them after the first generation?

**Comment by alessandroperilli** [comment]
> How about this, let the dropdown show option 3 by default, and then only show the resolution of the corresponding model after the first generation? 

This would be a graceful compromise!

**Comment by receyuki** [comment]
Ok, I will start writing this feature after posting this custom node on reddit.

**Comment by alessandroperilli** [comment]
The new version of the node is fantastic. Thank you.
