### ISSUE TITLE
[BUG] - Image not analyzed after load

### ISSUE THREAD

**Issue by isben** [receyuki/comfyui-prompt-reader-node#7]
### Description

I updated all custom nodes and installed SD-Prompt Reader Node and then restarted ComfyUI.
I cleared the workspace and added the SD Prompt Reader Node and then selected a jpeg file dowloaded from Civitai. Loading that file in the stand alone app or on the ComfyUI workspace shows the prompts and metadata of the image.
However, uploading it into the SD Prompt Reader Node, displays the image at the bottom of the node, but doesn't fill the prompt boxes nor does it activate any of the outputs.

### Reproduction steps

- Click the Clear button in the ComfyUI menu
- Add a SD Prompt Reader Node on the workspace
- Click the upload field in the node
- Select an image file
- The image is displayed at the bottom of the node but nothing else happens: no prompt added to the prompt boxes, no output made active. This happens with files that show information when loaded into the stand-alone SD Prompt Reader app

### Image file

![workflow](https://github.com/receyuki/comfyui-prompt-reader-node/assets/2913799/fa5a91d0-142a-41a7-a7cf-22c5cc230cd1)

### Version

1.0.0

**Comment by receyuki** [comment]
Please connect this node to any other node (either directly connect the IMAGE to any Saver or connect any parameter to your workflow, as long as you can make this node run). The content on the reader ui will only be updated after one generation, I know this is confusing but there is currently no better solution.

**Comment by receyuki** [comment]
ClipTextEncode++ seems very similar to the original ClipTextEncode, so supporting this node should not be difficult, I’m may add support for it. However, in fact, if you use the Prompt Saver node correctly, all parameters will be readable by the Reader, regardless of what custom nodes are used.

About how to use the Prompt Saver, you can refer to the connection of the [example workflow](https://github.com/receyuki/comfyui-prompt-reader-node/blob/main/workflows/example_workflow.json). Put simply, you need to convert the Saver and KSampler parameters from widgets to input (right-click the node and select options like “convert steps to input”). Then, set the parameters on the Generator and output the parameters to both KSampler and the Saver at the same time (believe me, it might be a bit troublesome for the first time, but personally, I think it’s more convenient than the traditional method after the connection is completed).
![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/d8ab853c-679e-4666-b156-3ae19ec49593)

**Comment by isben** [comment]
Thanks for the follow up.

We have some progress, but we are still far from fully clarifying the process.

- The schema you provided has a lot of the links overlapping each other. Using straight lines maybe cleaner when you know what you are doing but doesn't show what you were intending to do, when trying to explain things. Same remark for packing all the node next to each other. Had your schema included the workflow, we at least try to load it and understand what you have been doing.
- Even after running the workflow, I'm unable to link the MODEL_NAME output in the SD Prompt Generator name to the model_name input in the SD Prompt Saver node.
- The Checkpoint used by the uploaded image is clearly displayed in the SD Prompt Reader node. The SD Prompt Generator obviously doesn't ever get updated. It seems that you expect us to look into the info in the Reader node and paste that in the Generator. Can't it be made automatic? Even better, can you extract the AIR for those images published on CivitAI that have it, so we could inject that into a CivitAI Checkpoint Loader to automatically upload the model in case it is missing.
- Same question for the Clip, the VAE, the Sampler and the Scheduler.
- Why is the Generator needed anyway?
- What the purpose of the FILE_NAME and SETTINGS outputs in the Reader node? Same questions for the PARAMETERS output in the Generator.

Here is the workflow I came up with. Feel free to point out what's wrong with it.

[workflow2.json](https://github.com/receyuki/comfyui-prompt-reader-node/files/13193707/workflow2.json)

**Comment by receyuki** [comment]
- The schema above is just a preview image, and I’ve already posted the hyperlink to the example workflow. And I also mentioned the example workflow at the end of the readme. To prevent more misunderstandings, I will change the preview image in the readme to a version with a workflow embedded. Since the workflow you’ve provided is almost the same as the example workflow, and everything is working fine on my end, I’ll explain your other questions one by one.


Here ↓
<img width="349" alt="截屏2023-11-01 上午1 03 14" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/d0f0ecae-95bd-462f-aed5-6f5c95368da1">  

1. This is a known ComfyUI bug which happens when your model list changes (either models are deleted or added). The simplest solution is to reload the page (and you may also want to restart the ComfyUI server first).
2. The file name of the model is not unique, only the hash of the model can ensure the uniqueness of the model. However, in most cases, the metadata will not contain the model’s hash, so I hope users will take the model file name displayed in the Reader as a reference and choose the model themselves in the generator.
3. The metadata of most images does not contain information about clip and vae.
4. Different tool has different support and naming for different samplers and schedulers, so it’s possible that the tool you’re using doesn't support the sampler and scheduler used for image generation. Even when the sampler used to generate the image is supported, there might be inconsistency in naming. Due to the high update frequency of the sampler and scheduler, adding a naming map between different tools would significantly increase my workload.
5. >Since it's not possible to directly extract metadata from KSampler, it is necessary to use the Parameter Generator Node to generate parameters and simultaneously output them to both the Prompt Saver Node and KSampler.
6. It’s just left for those who need it. For instance, some people choose to output them to the terminal through other nodes. If you don’t need them, you can ignore them.

**Comment by isben** [comment]
Thanks for your explanations. It makes a lot more sense now.

**Comment by homeworkace** [comment]
Bumping because the screenshot in [this comment](https://github.com/receyuki/comfyui-prompt-reader-node/issues/7#issuecomment-1782949831) seems to be the closest thing to what I'm facing now.
![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/21036015/d4a68d3e-3711-4b6c-8606-f3a5f2b5c689)

Like OP my aim is to replicate settings from images done with the AUTOMATIC1111 client. The text fields seem to show that settings metadata exists in the source image and that the node is able to parse them, but all the output parameters except "IMAGE" and "MASK" are greyed out, which leaves me **unable to pass parameters like the prompt to a KSampler**. Maybe I'm just new to ComfyUI as a whole, but on the off-chance I encounter a bug I suppose it's worth asking.

**Comment by receyuki** [comment]
I've never encountered such a problem before. If you're unable to connect nodes, my suggestion would be to restart the server/create a new workflow/re-add nodes, because this problem seems to be unrelated to the reader.

If you're a newbie to comfyui, my example workflows may be helpful for you.
https://github.com/receyuki/comfyui-prompt-reader-node#example-workflow
